# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-07 11:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('team_name', models.CharField(max_length=30, null=True)),
                ('budget', models.FloatField(default=16)),
                ('changes_count', models.PositiveIntegerField(default=0)),
                ('refresh_changes', models.BooleanField(default=False, editable=False)),
                ('points', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
