# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-14 11:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
