# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-17 07:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('auth', '0008_alter_user_username_max_length'),
        ('accounts', '0003_auto_20181214_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('team_name', models.CharField(max_length=30, unique=True)),
                ('budget', models.PositiveIntegerField(default=10000000, editable=False)),
                ('changes_count', models.PositiveIntegerField(default=0, editable=False)),
                ('refresh_changes', models.BooleanField(default=False, editable=False)),
                ('points', models.PositiveIntegerField(default=0, editable=False)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
