# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-17 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20181217_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='team_name',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
