# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-12 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190311_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='adbanners',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
