# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-17 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20181217_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='team_name',
            field=models.CharField(blank=True, default=None, max_length=30),
        ),
    ]
