# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-20 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20181217_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='budget',
            field=models.PositiveIntegerField(default=10000000),
        ),
    ]
