# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-12 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190312_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adbanners',
            name='large_image',
            field=models.ImageField(upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='adbanners',
            name='medium_image',
            field=models.ImageField(default=1, upload_to='banners/'),
            preserve_default=False,
        ),
    ]
