# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-12 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190312_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adbanners',
            name='large_image',
            field=models.ImageField(help_text='Resolution 1140 x 90 px', upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='adbanners',
            name='medium_image',
            field=models.ImageField(help_text='Resolution 800 x 80 px', upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='adbanners',
            name='small_image',
            field=models.ImageField(help_text='Resolution 414 x 50 px', upload_to='banners/'),
        ),
    ]
