# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-06 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20190130_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_first_time',
            field=models.BooleanField(default=True),
        ),
    ]
