# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-06 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_profile_is_first_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_first_time',
        ),
    ]
