# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-12 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_profile_is_first_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='budget',
            field=models.PositiveIntegerField(default=10000000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='changes_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
