# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-16 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20190408_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='points',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
