version: '3'

services:
  web: 
    build: .
    ports:
      - 80:80
    volumes:
      - /var/log/app:/var/log/supervisor
      - /var/log/app/nginx:/var/log/nginx
    restart: always
    depends_on:
      - db    
    
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ohw2Eege
      MYSQL_DATABASE: fantasyhockey
      MYSQL_USER: fantasyhockey
      MYSQL_PASSWORD: xu2Cuosh
    volumes:
      - /var/log/app/mysql:/var/log/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
