version: '3'

services:
  web: 
    build: .
    ports:
      - 81:80
    volumes:
      - /var/log/app:/var/log/supervisor
      - /var/log/app/nginx:/var/log/nginx
      - /var/log/app/uwsgi:/var/log/uwsgi
      - /var/log/app/django/logs_prod:/home/docker/code/app/logs_prod
    restart: always
    depends_on:
      - db    
    command: ["./wait-port.sh", "db:3306", "--","./docker-entrypoint.sh"]
    
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ohw2Eege
      MYSQL_DATABASE: fantasyhockey
      MYSQL_USER: fantasyhockey
      MYSQL_PASSWORD: xu2Cuosh
    volumes:
      - /var/log/app/mysql:/var/log/mysql
      - /var/lib/mysql:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
