# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-31 05:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freeze_and_count', '0002_auto_20190130_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freeze',
            old_name='end',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='freeze',
            old_name='start',
            new_name='start_time',
        ),
    ]
