# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-13 06:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freeze_and_count', '0003_auto_20190131_1044'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Freeze',
        ),
    ]
