# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-07 11:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Captain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('Goal_Game', 'GOAL_FROM_THE_GAME'), ('Goal_Penalty', 'GOAL_FROM_THE_PENALTY'), ('Goal_Free_Kick', 'GOAL_FROM_THE_FREE_KICK'), ('Green_Card', 'GREEN_CARD'), ('Yellow_Card', 'YELLOW_CARD'), ('Red_Card', 'RED_CARD')], max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_of_tour', models.PositiveSmallIntegerField()),
                ('score', models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')])),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('bullitt_winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Bullitt_Winner', to='players.Club')),
                ('guest_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Guest', to='players.Club')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Home', to='players.Club')),
            ],
        ),
        migrations.CreateModel(
            name='Miss_Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('GK', 'GOALKEEPER'), ('DE', 'DEFENDER'), ('MF', 'MIDFIELDER'), ('FW', 'FORWARD')], max_length=2)),
                ('price', models.FloatField()),
                ('points', models.PositiveIntegerField(default=0, editable=False)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Club')),
            ],
        ),
        migrations.CreateModel(
            name='Result_Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0, editable=False)),
                ('player_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='players.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Result_Profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_captain', models.BooleanField(default=False)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Team_Temporary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer', models.CharField(choices=[('First_Time', 'FIRST_TIME'), ('From_Team', 'FROM_TEAM'), ('To_Team', 'TO_TEAM')], max_length=10)),
                ('timeout', models.DateTimeField(blank=True, null=True)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Player')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.PositiveIntegerField(default=2019)),
                ('number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('supposed_end_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='tour',
            unique_together=set([('season', 'number')]),
        ),
        migrations.AddField(
            model_name='team',
            name='tour_number_end',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tour_number_end', to='players.Tour'),
        ),
        migrations.AddField(
            model_name='team',
            name='tour_number_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tour_number_start', to='players.Tour'),
        ),
        migrations.AddField(
            model_name='team',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
        migrations.AddField(
            model_name='result_profiles',
            name='tour_number',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='players.Tour'),
        ),
        migrations.AddField(
            model_name='result_profiles',
            name='user_id',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
        migrations.AddField(
            model_name='result_players',
            name='tour_number',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='players.Tour'),
        ),
        migrations.AddField(
            model_name='miss_match',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='tour_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Tour'),
        ),
        migrations.AddField(
            model_name='event',
            name='match_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Game'),
        ),
        migrations.AddField(
            model_name='event',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Player'),
        ),
        migrations.AddField(
            model_name='captain',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Player'),
        ),
        migrations.AddField(
            model_name='captain',
            name='tour_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Tour'),
        ),
        migrations.AddField(
            model_name='captain',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=set([('user_id', 'player_id', 'tour_number_start')]),
        ),
        migrations.AlterUniqueTogether(
            name='result_profiles',
            unique_together=set([('user_id', 'tour_number')]),
        ),
        migrations.AlterUniqueTogether(
            name='result_players',
            unique_together=set([('player_id', 'tour_number')]),
        ),
        migrations.AlterUniqueTogether(
            name='miss_match',
            unique_together=set([('match_id', 'player_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='game',
            unique_together=set([('tour_number', 'game_of_tour', 'home_team', 'guest_team')]),
        ),
        migrations.AlterUniqueTogether(
            name='captain',
            unique_together=set([('user_id', 'tour_number')]),
        ),
    ]
