# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-22 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_auto_20181220_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('Goal_Game', 'GOAL_FROM_THE_GAME'), ('Goal_Penalty', 'GOAL_FROM_THE_PENALTY'), ('Goal_Free_Kick', 'GOAL_FROM_THE_FREE_KICK'), ('Green_Card', 'GREEN_CARD'), ('Yellow_Card', 'YELLOW_CARD'), ('Red_Card', 'RED_CARD')], default='Goal_Game', max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Guest', to='players.Club')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Home', to='players.Club')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('position', models.CharField(choices=[('GK', 'GOALKEEPER'), ('DE', 'DEFENDER'), ('MF', 'MIDFIELDER'), ('FW', 'FORWARD')], default='MF', max_length=2)),
                ('number', models.CharField(default='99', max_length=2)),
                ('price', models.PositiveIntegerField(default=1000000)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.ManyToManyField(blank=True, to='players.Player')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='match_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Game'),
        ),
        migrations.AddField(
            model_name='event',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Player'),
        ),
    ]
