# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-23 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_auto_20181223_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='player_id',
        ),
        migrations.AddField(
            model_name='team',
            name='player_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='players.Player'),
        ),
    ]
