# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-24 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_profile_nickname'),
        ('players', '0004_auto_20181223_1255'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='result',
            unique_together=set([('user_id', 'tour')]),
        ),
    ]
