# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-12 13:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_auto_20190311_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_club', models.ForeignKey(help_text='Клуб, из которого ушёл игрок.', on_delete=django.db.models.deletion.CASCADE, to='players.Club')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Player')),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='bullitt_winner',
            field=models.ForeignKey(blank=True, help_text='Победитель по буллитам. Поле заполняется только когда матч закончен в ничью', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Bullitt_Winner', to='players.Club'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_of_tour',
            field=models.PositiveSmallIntegerField(help_text='Номер игры в туре (в туре может пройти больше двух игр)'),
        ),
        migrations.AlterField(
            model_name='game',
            name='guest_team',
            field=models.ForeignKey(help_text='Команда, которая играла на выезде', on_delete=django.db.models.deletion.CASCADE, related_name='Guest', to='players.Club'),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(help_text='Команда, которая играла дома', on_delete=django.db.models.deletion.CASCADE, related_name='Home', to='players.Club'),
        ),
        migrations.AlterField(
            model_name='game',
            name='score',
            field=models.CharField(blank=True, help_text='Очки, записанные через запятую БЕЗ пробелов, например "2,1"', max_length=5, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AlterField(
            model_name='game',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='Время, когда игра начнётся. Время вписывается по часовому поясу UTC.', null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='tour_number',
            field=models.ForeignKey(help_text='Тур, в который прошла игра', on_delete=django.db.models.deletion.CASCADE, to='players.Tour'),
        ),
        migrations.AlterField(
            model_name='miss_match',
            name='match_id',
            field=models.ForeignKey(help_text='Матч, который пропустил игрок', on_delete=django.db.models.deletion.CASCADE, to='players.Game'),
        ),
        migrations.AlterField(
            model_name='miss_match',
            name='player_id',
            field=models.ForeignKey(help_text='Игрок, пропустивший матч', on_delete=django.db.models.deletion.CASCADE, to='players.Player'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='name',
            field=models.CharField(blank=True, help_text='Имя тура заполняется только во время плей-офф. Например, "1/8 финала"', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='number',
            field=models.PositiveSmallIntegerField(help_text='Номер тура. Если это матч плей-офф, номер всё равно вбивается. Он будет использован, при подсчёте очков.'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='season',
            field=models.PositiveIntegerField(default=2019, help_text='Год тура'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='Начало дедлайна в туре.', null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='supposed_end_time',
            field=models.DateTimeField(blank=True, help_text='Предположительные время конца дедлайна в туре. Показывается для пользователя, когда ему ждать результатов подсчёта очков.', null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='tour_number_end',
            field=models.ForeignKey(help_text='Тур, в котором игрок сыграл последний матч за клуб', on_delete=django.db.models.deletion.CASCADE, related_name='Tour_Number_End', to='players.Tour'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='tour_number_start',
            field=models.ForeignKey(help_text='Тур, в котором игрок начал играть за клуб (если с начала сезона, то ставится 1 тур.', on_delete=django.db.models.deletion.CASCADE, related_name='Tour_Number_Start', to='players.Tour'),
        ),
    ]
