# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-12 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_auto_20190312_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='old_club',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='player_id',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='tour_number_end',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='tour_number_start',
        ),
        migrations.DeleteModel(
            name='Transfer',
        ),
    ]
