# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-24 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_auto_20181224_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='tour_end',
            field=models.SmallIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='team',
            name='tour_start',
            field=models.SmallIntegerField(default=1),
        ),
    ]
