# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-13 07:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_auto_20190312_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Players_Team_in_Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Club')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Player')),
                ('tour_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Tour')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='players_team_in_tour',
            unique_together=set([('player_id', 'tour_number', 'club')]),
        ),
    ]
