# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-26 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_auto_20181226_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='tour_end',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
