# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-28 07:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_profile_nickname'),
        ('players', '0008_auto_20181226_1607'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=set([('user_id', 'player_id')]),
        ),
    ]
