# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-21 12:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0010_auto_20190319_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='score',
            field=models.CharField(blank=True, help_text='Очки, записанные через запятую БЕЗ пробелов, например "2,1"', max_length=5, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
