# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-31 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20190130_1137'),
        ('players', '0011_tour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='tour',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='game',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='player',
            name='number',
        ),
        migrations.AddField(
            model_name='game',
            name='tour_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.Tour'),
        ),
        migrations.AddField(
            model_name='result',
            name='tour_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.Tour'),
        ),
        migrations.AddField(
            model_name='team',
            name='tour_number_end',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tour_number_end', to='players.Tour'),
        ),
        migrations.AddField(
            model_name='team',
            name='tour_number_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tour_number_start', to='players.Tour'),
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together=set([('user_id', 'tour_number')]),
        ),
        migrations.RemoveField(
            model_name='result',
            name='tour',
        ),

        migrations.RemoveField(
            model_name='team',
            name='tour_end',
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=set([('user_id', 'player_id', 'tour_number_start')]),
        ),
        migrations.RemoveField(
            model_name='team',
            name='tour_start',
        ),

    ]
