# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-29 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0011_auto_20190321_1208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='miss_match',
            options={'verbose_name_plural': 'Miss_Matches'},
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(help_text='Введите имя клуба. Именно так оно будет отображаться везде.', max_length=100),
        ),
        migrations.AlterField(
            model_name='tour',
            name='number',
            field=models.PositiveSmallIntegerField(help_text='Номер тура. Туры идут по порядку. Если это матч плей-офф, номер всё равно вбивается. Он будет использован, при подсчёте очков.'),
        ),
    ]
