# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-01 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0012_auto_20190329_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='end_time',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
