# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-31 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0012_auto_20190131_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='tour_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='players.Tour'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='game',
            unique_together=set([('tour_number', 'game')]),
        ),
    ]
