# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-31 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0013_auto_20190131_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='tour_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='players.Tour'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='player_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='players.Player'),
            preserve_default=False,
        ),
    ]
