# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-31 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0014_auto_20190131_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('GK', 'GOALKEEPER'), ('DE', 'DEFENDER'), ('MF', 'MIDFIELDER'), ('FW', 'FORWARD')], max_length=2),
        ),
        migrations.AlterField(
            model_name='player',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='surname',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
