# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-31 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0015_auto_20190131_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
