# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-31 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0016_auto_20190131_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='kind',
            field=models.CharField(choices=[('Goal_Game', 'GOAL_FROM_THE_GAME'), ('Goal_Penalty', 'GOAL_FROM_THE_PENALTY'), ('Goal_Free_Kick', 'GOAL_FROM_THE_FREE_KICK'), ('Green_Card', 'GREEN_CARD'), ('Yellow_Card', 'YELLOW_CARD'), ('Red_Card', 'RED_CARD')], max_length=14),
        ),
    ]
