# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-31 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0017_auto_20190131_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='season',
            field=models.PositiveIntegerField(default=2019),
        ),
        migrations.AlterField(
            model_name='tour',
            name='number',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='tour',
            unique_together=set([('season', 'number')]),
        ),
    ]
