# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-01 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0018_auto_20190131_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='supposed_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
