# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-01 06:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0019_tour_supposed_end_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='game',
            unique_together=set([('tour_number', 'game', 'home_team', 'guest_team')]),
        ),
    ]
