# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-01 10:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0020_auto_20190201_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='bullitt_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Bullitt_Winner', to='players.Club'),
        ),
        migrations.AddField(
            model_name='game',
            name='score',
            field=models.CharField(default=(1, 1), max_length=5, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
            preserve_default=False,
        ),
    ]
