# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-01 11:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0021_auto_20190201_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game',
            new_name='game_of_tour',
        ),
        migrations.AlterUniqueTogether(
            name='game',
            unique_together=set([('tour_number', 'game_of_tour', 'home_team', 'guest_team')]),
        ),
    ]
