# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-02 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0022_auto_20190201_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Miss_Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Game')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Player')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='miss_match',
            unique_together=set([('match_id', 'player_id')]),
        ),
    ]
