# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-04 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0023_auto_20190202_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='tour_number',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='players.Tour'),
        ),
        migrations.AlterField(
            model_name='result',
            name='user_id',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
    ]
