# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-04 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0024_auto_20190204_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result_Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0, editable=False)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Player')),
                ('tour_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Tour')),
            ],
        ),
        migrations.RenameModel(
            old_name='Result',
            new_name='Result_Profiles',
        ),
        migrations.AlterUniqueTogether(
            name='result_players',
            unique_together=set([('player_id', 'tour_number')]),
        ),
    ]
