# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-05 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0025_auto_20190204_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='points',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='result_players',
            name='player_id',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='players.Player'),
        ),
        migrations.AlterField(
            model_name='result_players',
            name='tour_number',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='players.Tour'),
        ),
    ]
