# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-05 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0026_auto_20190205_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='end_time',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
