# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-08 06:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_profile_is_first_time'),
        ('players', '0028_auto_20190205_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_Temporary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer', models.CharField(choices=[('First_Time', 'FIRST_TIME'), ('From_Team', 'FROM_TEAM'), ('To_Team', 'TO_TEAM')], max_length=10)),
                ('timeout', models.DateTimeField(blank=True, null=True)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Player')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
    ]
