# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-13 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0030_auto_20190213_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='player_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.Player'),
        ),
    ]
