# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-25 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0032_auto_20190221_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_captaion',
            field=models.BooleanField(default=False),
        ),
    ]
