# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-25 08:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0033_team_is_captaion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='is_captaion',
            new_name='is_captain',
        ),
    ]
