# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-27 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0034_auto_20190225_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='player_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='players.Player'),
            preserve_default=False,
        ),
    ]
