# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-27 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0035_auto_20190227_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
