# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-27 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20190221_1851'),
        ('players', '0036_tour_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Captain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Player')),
                ('tour_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Tour')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='captain',
            unique_together=set([('user_id', 'tour_number', 'player_id')]),
        ),
    ]
