# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-06 10:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0038_auto_20190227_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='score',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
