# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-06 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0039_auto_20190306_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
